version: '3'
services:
  database:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: achatdb   
    ports:
      - 3306:3306
    networks:
     - projectnetwork
     
  spring-boot:
    image: ouellani/springdevops
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - projectnetwork 
    restart: on-failure     
  
networks:
  projectnetwork:
